spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/emzio/Dokumenty/projekty/ToDoApi/todo_api/todo-testdb'
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'